-- ============================================================================
-- EV CHARGER IoT PLATFORM — UNIFIED TiDB CLOUD SCHEMA
-- Single cluster: data plane + context plane
-- ============================================================================

-- ============================================================================
-- DATA PLANE: IoT telemetry, Flink windows, outage catalog
-- ============================================================================

-- Raw telemetry from OCPP chargers (Flink sink target)
CREATE TABLE charger_telemetry (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  charger_id      VARCHAR(32)   NOT NULL,
  connector_id    TINYINT       NOT NULL DEFAULT 1,
  ts              TIMESTAMP(3)  NOT NULL,
  status          ENUM('Available','Preparing','Charging','SuspendedEVSE',
                       'SuspendedEV','Finishing','Faulted','Unavailable')  NOT NULL,
  transaction_id  VARCHAR(64),
  -- Meter values
  energy_wh       BIGINT,
  power_w         INT,
  voltage_v       DECIMAL(6,2),
  current_a       DECIMAL(6,2),
  soc_percent     TINYINT UNSIGNED,
  -- Diagnostics
  temp_c          DECIMAL(5,2),
  error_code      VARCHAR(32)   DEFAULT 'NoError',
  vendor_error    VARCHAR(128),
  fan_rpm         INT,
  earth_leak_ma   DECIMAL(5,2),
  contactor_cycles INT,
  signal_dbm      SMALLINT,
  -- Indexes
  INDEX idx_charger_ts      (charger_id, ts),
  INDEX idx_status_ts       (status, ts),
  INDEX idx_error           (error_code, ts)
);

-- Flink tumbling window aggregates (5-minute windows)
-- Each row summarises one charger's behaviour over a 5-min window
CREATE TABLE charger_windows (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  charger_id      VARCHAR(32)   NOT NULL,
  window_start    TIMESTAMP     NOT NULL,
  window_end      TIMESTAMP     NOT NULL,
  -- Aggregated features
  msg_count       INT,
  avg_power_w     DECIMAL(10,2),
  max_power_w     INT,
  min_voltage_v   DECIMAL(6,2),
  max_voltage_v   DECIMAL(6,2),
  voltage_stddev  DECIMAL(6,3),
  avg_current_a   DECIMAL(6,2),
  max_temp_c      DECIMAL(5,2),
  avg_temp_c      DECIMAL(5,2),
  error_count     INT           DEFAULT 0,
  status_changes  INT           DEFAULT 0,
  distinct_errors JSON,
  avg_fan_rpm     INT,
  max_earth_leak  DECIMAL(5,2),
  -- Flink-generated anomaly flags
  anomaly_flags   JSON,
  anomaly_score   DECIMAL(4,3)  DEFAULT 0.000,
  -- Vector embedding of the window signature
  -- Generated by the embedding service on INSERT
  signature_vec   VECTOR(384),
  -- Indexes
  INDEX idx_charger_window  (charger_id, window_start),
  INDEX idx_anomaly         (anomaly_score DESC, window_start),
  VECTOR INDEX idx_sig_vec  ((VEC_COSINE_DISTANCE(signature_vec)))
);

-- Historical outage catalog (curated ground truth)
CREATE TABLE outage_catalog (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  pattern_id      VARCHAR(32)   NOT NULL UNIQUE,
  pattern_name    VARCHAR(128)  NOT NULL,
  category        ENUM('electrical','mechanical','firmware','network',
                       'thermal','environmental','unknown') NOT NULL,
  root_cause      TEXT          NOT NULL,
  symptoms        JSON          NOT NULL,
  resolution      TEXT          NOT NULL,
  severity        ENUM('degraded','offline','safety') NOT NULL,
  affected_models JSON,
  affected_firmware JSON,
  occurrence_count INT          DEFAULT 1,
  last_seen       TIMESTAMP,
  created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  -- Vector embedding of pattern description
  signature_vec   VECTOR(384),
  INDEX idx_category        (category, severity),
  VECTOR INDEX idx_outage_vec ((VEC_COSINE_DISTANCE(signature_vec)))
);

-- Charger metadata (static / slowly changing)
CREATE TABLE charger_registry (
  charger_id      VARCHAR(32)   PRIMARY KEY,
  site_id         VARCHAR(64)   NOT NULL,
  model           VARCHAR(64),
  manufacturer    VARCHAR(64),
  firmware_version VARCHAR(16),
  install_date    DATE,
  lat             DECIMAL(9,6),
  lon             DECIMAL(9,6),
  connector_count TINYINT       DEFAULT 1,
  max_power_kw    DECIMAL(5,1),
  environment     ENUM('indoor','outdoor_sheltered','outdoor_exposed','coastal'),
  last_maintenance DATE,
  total_sessions  INT           DEFAULT 0,
  total_energy_kwh BIGINT       DEFAULT 0,
  INDEX idx_site            (site_id),
  INDEX idx_model           (manufacturer, model)
);


-- ============================================================================
-- CONTEXT PLANE: Agent reasoning, fleet memory, session state
-- ============================================================================

-- Agent reasoning chains — OUTCOME RECORDS ONLY
-- Rows are written ONLY when an investigation reaches a conclusion:
-- confirmed diagnosis, dismissed hypothesis, escalation, or promoted pattern.
-- Intermediate reasoning is NOT persisted here — it lives in the context window
-- and in investigation_summary on session_state.
CREATE TABLE agent_reasoning (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  charger_id      VARCHAR(32),
  site_id         VARCHAR(64),
  session_id      VARCHAR(64)   NOT NULL,
  created_at      TIMESTAMP(3)  DEFAULT CURRENT_TIMESTAMP(3),
  -- What the agent observed
  observation     TEXT          NOT NULL,
  -- What the agent hypothesises
  hypothesis      TEXT,
  -- Which data plane rows support this
  evidence_refs   JSON,
  -- How confident the agent is (0.00 to 1.00)
  confidence      DECIMAL(3,2)  DEFAULT 0.50,
  -- Investigation status
  resolution      ENUM('confirmed','dismissed','escalated','promoted')
                                NOT NULL,
  resolved_at     TIMESTAMP     NULL,
  -- Tags for filtering
  tags            JSON,
  -- Vector embedding of observation + hypothesis
  -- Populated asynchronously by TiCDC + embedding service, NOT at insert time.
  reasoning_vec   VECTOR(384),
  -- Indexes
  INDEX idx_charger_reasoning (charger_id, created_at DESC),
  INDEX idx_session          (session_id, created_at),
  INDEX idx_resolution       (resolution, created_at DESC),
  VECTOR INDEX idx_reasoning_vec ((VEC_COSINE_DISTANCE(reasoning_vec)))
);

-- Fleet-wide learned knowledge (long-term memory)
-- Patterns the agent has discovered across many investigations.
-- This is the "memory store" — persists across all sessions.
CREATE TABLE fleet_memory (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  -- What kind of knowledge
  category        ENUM('pattern','preference','hardware_note','site_context',
                       'firmware_bug','seasonal','operational_rule') NOT NULL,
  -- Scope: 'global', 'site:SITE-DUB-07', 'model:ABB-Terra-54'
  scope           VARCHAR(128)  NOT NULL DEFAULT 'global',
  -- The knowledge itself
  content         TEXT          NOT NULL,
  -- Provenance: which reasoning chains produced this
  source_refs     JSON,
  -- Reliability
  confidence      DECIMAL(3,2)  DEFAULT 0.70,
  supporting_evidence_count INT DEFAULT 1,
  -- Usage tracking
  access_count    INT           DEFAULT 0,
  last_accessed   TIMESTAMP     NULL,
  -- Lifecycle
  status          ENUM('active','deprecated','superseded') DEFAULT 'active',
  superseded_by   BIGINT        NULL,
  -- Vector embedding
  memory_vec      VECTOR(384),
  INDEX idx_scope_status    (scope, status),
  INDEX idx_category        (category, status),
  VECTOR INDEX idx_memory_vec ((VEC_COSINE_DISTANCE(memory_vec)))
);

-- Session state (short-lived, tracks active investigations)
CREATE TABLE session_state (
  session_id      VARCHAR(64)   PRIMARY KEY,
  user_id         VARCHAR(64),
  started_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  last_active     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  -- What the session is focused on
  focus_chargers  JSON,
  focus_site      VARCHAR(64),
  investigation_summary TEXT,
  -- Token budget management
  token_budget    INT           DEFAULT 4000,
  tokens_used     INT           DEFAULT 0,
  -- Context assembly cache
  last_context_hash VARCHAR(64),
  INDEX idx_user            (user_id, last_active DESC),
  INDEX idx_active          (last_active)
);

-- Pre-assembled context snapshots (cached prompt fragments)
-- Rebuilt periodically to avoid re-computing on every agent call
CREATE TABLE context_snapshots (
  id              BIGINT AUTO_RANDOM PRIMARY KEY,
  -- What this snapshot covers
  entity_type     ENUM('charger','site','fleet_summary') NOT NULL,
  entity_id       VARCHAR(64)   NOT NULL,
  snapshot_type   ENUM('profile','recent_anomalies','maintenance_history',
                       'performance_baseline','active_investigations') NOT NULL,
  -- The pre-assembled text
  content         TEXT          NOT NULL,
  -- Approximate token count of content
  token_count     INT           NOT NULL DEFAULT 0,
  -- Lifecycle
  created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  expires_at      TIMESTAMP     NOT NULL,
  is_stale        BOOLEAN       DEFAULT FALSE,
  -- Vector for semantic retrieval
  snapshot_vec    VECTOR(384),
  -- Indexes
  INDEX idx_entity          (entity_type, entity_id, snapshot_type),
  INDEX idx_expires         (expires_at),
  UNIQUE INDEX idx_unique_snap (entity_id, snapshot_type)
);
